NODES = 4;                 # the amount of nodes in the system
USERS = 30;                 # the amount of users in the systme
THETA1 = 2;              # theta1 used in the Puk caluclations
THETA2 = 3;               # thete2 used in the Guk calculations
G0 = pow(10,-13);                     # G0 used in the Ruk calculations
TIMESLOTDURATION = 2000;      # the duration of each timeslot used in the congestion calculation
BETA = 0.7;                    # beta factor used in updating the probabilties during the SLA
BANDWIDTH = 5000000;
MAXRANGE = 1;
MINRANGE = 0;